### ISSUE TITLE
Why is memory.profiling off in profvis.R?

### ISSUE THREAD

**Issue by navdeep-G** [rstudio/profvis#33]
I noticed that memory.profiling is not part of the input parameters for profvis's use of Rprof and thus is set to `FALSE` per Rprof's default settings. See below:

`Rprof(prof_output, interval = interval, line.profiling = TRUE,
          gc.profiling = TRUE)`

Is there a reason for this? Will profvis provide memory profiling in the future? If not, I can give it a shot via pull request.

Cheers,
Navdeep

**Comment by javierluraschi** [comment]
We have short-term plans to add "Call graph", "Functions", "Lines" and "Hot paths"... not memory profiling that I know off.

Personally speaking, this sounds like a great feature. I believe you will have to sign a contributors agreement with your PR, we can help you with that when the time comes. Regarding ui entry points, it seems appropriate to me to add a new tab to present memory results. The tabs PR just went in a few days ago: https://github.com/rstudio/profvis/pull/30.

**Comment by PeteHaitch** [comment]
Memory profiling would be great - it was very useful to me (and others I know) in https://github.com/hadley/lineprof

**Comment by javierluraschi** [comment]
Hey @navdeep-G, have you already started with the memory implementation? We've been thinking about what features to add/improve and memory profiling keeps coming back. I'm asking since it may be worth helping implement this over other features, let me know where you are and if there is anything I can do to help.

**Comment by navdeep-G** [comment]
Hi @javierluraschi , I haven't started on this yet but plan to either today or this weekend. Which `.R` file would be the place to start in terms of refactoring? I am assuming `profvis.R` entails all I need to start with but any input in this regard would be great.

**Comment by javierluraschi** [comment]
For sure, here are a couple pointers I think you will need:

- [ ] **Enable memory profiling**: You would want to start profiling memory by adding the `memory.profiling = TRUE` entry here: https://github.com/rstudio/profvis/blob/master/R/profvis.R#L74
- [ ] **Parse memory data**: The memory data gets generated in Rprod files for each line in this format: `:memory:memory:memory:dups:"stack trace 1" "stack trace 2" "stack trace n`. You will need to extract this data for each line in `parse.R`. Line 39 from https://github.com/rstudio/profvis/blob/master/R/parse.R#L39 will need to account for this and the `mapply` over `prof_data` would have to return the memory allocation `memalloc`. In order to convert memory to megabytes you can use this code `(prof$small_v + prof$big_v + prof$nodes) / 1024 ^ 2)` from https://github.com/hadley/lineprof/blob/d034a7e0116886a997eae211efb932bf6ea73cee/R/profile.R#L61. Finally, since we want to render memory increments, not total memory allocation, we would have to map `prof_data[[]]$memalloc` into `prof_data[[]]$meminc`, we can use `diff` in a similar way than `lineprof` does. This will be enough to pass the `meminc` memory data all the way to javascript. More info on the structure of Rprof memory can be found in the R sources at this location: https://github.com/wch/r-source/blob/be7197f/src/main/eval.c#L228-L244
- [ ] **Visualize memory data**: Once the `meminc` is assigned per line, you can aggregate this data in d3 in a simular way that `sumTime` gets computed (see https://github.com/rstudio/profvis/blob/master/inst/htmlwidgets/lib/profvis/profvis.js#L1535). In order to visualize this, I would say we add a new column with the MB and the percent in the same way we visualize time: https://github.com/rstudio/profvis/blob/master/inst/htmlwidgets/lib/profvis/profvis.js#L209

My plan is to wrap up next week, so let's sync after the weekend to see if there is something else I can help to get this implemented. Thanks for suggesting this and giving it a shot @navdeep-G!

**Comment by javierluraschi** [comment]
@navdeep-G here are instructions to the contributors agreement: https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md - Would you mind filling this pdf and send it to JJ at your earliest convenience?

**Comment by javierluraschi** [comment]
@navdeep-G planning to work on this today, if you had a chance to spend some time here, send a pr our way. Otherwise, we could get some help testing this and providing feedback.

**Comment by navdeep-G** [comment]
@javierluraschi Haven't had a chance to get to this. Bogged down with other work. Sorry!

**Comment by javierluraschi** [comment]
@navdeep-G totally understandable, thanks for the message!

**Comment by javierluraschi** [comment]
Working on a PR: https://github.com/rstudio/profvis/pull/39 - We can close this issue now.
