### ISSUE TITLE
In RStudio, double-clicking on <expr> code results in error

### ISSUE THREAD

**Issue by wch** [rstudio/profvis#47]
Double-clicking on `<expr>` code results in an error because RStudio tries to open the file. It shouldn't try to open a `<expr>` "file".

![image](https://cloud.githubusercontent.com/assets/86978/14960264/7b81b0a6-1059-11e6-926f-9dd44c69fdfa.png)

**Comment by javierluraschi** [comment]
@wch the current behavior is that RStudio checks for the file to exist and if it does not, it disables the "go to source" toolbar menu. However, double clicking forces RStudio to try to open this file and always gives feedback back to the given double-click, in this case, an error. I think is consistent to always trigger something on double click rather than doing a no-op, but I see your point. This can get annoying since this error will trigger for all lines with no sources. The fix would be in RStudio, so I opened a bug there, we can probably close this one.

**Comment by wch** [comment]
@javierluraschi One other thing that might come up when you fix this -- I noticed that when when a line in `<expr>` is double-clicked, it results in some text being selected, as you can see in the screenshot. For other files (ones that actually exist), when you double-click, the text is momentarily selected, but then gets unselected, which is better.

**Comment by javierluraschi** [comment]
@wch removing the error prompt for missing sources for `<expr>` has been removed from the IDE.

**Comment by wch** [comment]
Great!
