### ISSUE TITLE
profvis breaks when last line ends in comment

### ISSUE THREAD

**Issue by ryanatanner** [rstudio/profvis#88]
When the last line in a block is a comment, or ends with a comment, using the RStudio IDE, highlighting code, and clicking **Profile --> Profile Selected Lines**, or using shortcut (Ctrl+Shift+Alt+P) results in a command with the closing curly bracket and parentheses commented. 

    profvis::profvis({1:1e9 # ends in a comment})

Easy enough to make work by just typing a curly bracket and parentheses in the console on a newline, but would be nice if it added the newline when the selected code ended with a comment.

**Comment by ryanatanner** [comment]
Not sure if this belongs here or in rstudio/rstudio

**Comment by wch** [comment]
This is the right place to report it.

**Comment by wch** [comment]
Hm, now that I look at it more closely, it does seem like an IDE issue.

The problem is that if this code is selected and then **Profile Selected Lines** is used:

```R
1:1e9 # ends in a comment
```

It turns into this in the console, where the `})` is parsed as part of the comment:

```R
profvis::profvis({1:1e9 # ends in a comment})
```


@jmcphers, @javierluraschi is it possible to change the IDE's behavior so that if the code ends in a comment, it puts the `})` on the next line?

**Comment by kevinushey** [comment]
I'll file this on the RStudio bug tracker -- thanks for reporting!

**Comment by lionel-** [comment]
Reported in rstudio/rstudio#8407.
